[project]
name = "orm-fasrapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pymysql>=1.1.2",
    "sqlalchemy>=2.0.43",
]
